### ISSUE TITLE
Error when setting tolerance for function value with keyword argument

### ISSUE THREAD

**Issue by tobiassalz** [JuliaOpt/Optim.jl#109]
I am setting up the following optimization problem (problem occurs with other methods as well, such as nelder mead): 

optresult = Optim.optimize((num) -> eqmapping(num,0),vec(param0),method = :cg,ftol=200)

I get the following error:

ERROR: `MultivariateOptimizationResults{T,N}` has no method matching MultivariateOptimizationResults{T,N}(::ASCIIString, ::Array{Float64,1}, ::Array{Float64,1}, ::Float64, ::Int64, ::Bool, ::Bool, ::Float64, ::Bool, ::Int64, ::Bool, ::Float64, ::OptimizationTrace, ::Int64, ::Int64)
 in cg at /home/myname/.julia/v0.3/Optim/src/cg.jl:273
 in optimize at /home/myname/.julia/v0.3/Optim/src/optimize.jl:437

The error is not there when I leave out ftol. Am I doing something wrong?

Versioninfo:

Julia Version 0.3.5
Commit a05f87b* (2015-01-08 22:33 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz
  WORD_SIZE: 64
  BLAS: libopenblas (NO_LAPACK NO_LAPACKE DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: liblapack.so.3
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

**Comment by johnmyleswhite** [comment]
I suspect this argument isn't exposed in the API. Subsuming this issue into a broader API redesign.

**Comment by pkofod** [comment]
`ftol` is indeed not exposed in the current API, you have to use `nelder_mead()` which is about to get deprecated. After #149 this should be put into a `OptimizationOptions` call in `optimize`.

**Comment by pkofod** [comment]
`optimize(vec -> sumabs2(vec)^2, [1,1.]; method = BFGS(), ftol = 1e-1l)` works now, you can also use an `OptimizationOptions()` positional argument, see the updated README.md. A new version isn't tagged, so you have to `Pkg.checkout("Optim")` to use this right now.
