### ISSUE TITLE
Maximum optimization time limit

### ISSUE THREAD

**Issue by multidis** [JuliaOpt/Optim.jl#117]
It often happens in particular with `fminbox` (calling `cg`) that optimization does not converge for a very long time (days) while the problem setup does not allow increasing various (objective, variable) tol-settings. This may happen once in e.g. 100 runs of the same problem and calls for a compute time limit option (`NLopt` has such an option in its C-code I think).

This has been recently discussed
http://julia-programming-language.2336112.n4.nabble.com/fminbox-getting-quot-stuck-quot-td12163.html
https://groups.google.com/d/topic/julia-opt/kQg3ub5EH74/discussion

Would a scheduled task initiated right before the optimization call be helpful to enforce the time limit? I am thinking similar to [this](https://groups.google.com/forum/#!starred/julia-users/WOXrzOnbwoI) with e.g. a variable change in place of interrupt-call, and to have `fminbox` check that variable at each step to see if it can proceed?

```
@schedule begin
    sleep(time_limit)
    if optim_not_converged
        terminate = TRUE
    end
 end
```

**Comment by johnmyleswhite** [comment]
A cheap approximation to this would be to enforce a time limit at the end of each iteration. Once you've used up the budget, you stop iterating. That doesn't give you tight time limits, but it's a decent start and much less complex to implement.

**Comment by johnmyleswhite** [comment]
We should add this.

**Comment by pkofod** [comment]
I guess the question is if this needs to be embedded in Optim, or if the callback-version of this (see the bottom of #266 )

**Comment by johnmyleswhite** [comment]
I don't see why using callbacks is superior to building this into Optim.

**Comment by pkofod** [comment]
I guess you're right. I can add the soft limit to the refactor PR.

**Comment by pkofod** [comment]
It's on master see https://github.com/JuliaOpt/Optim.jl/blob/ccc51d73621988265f77b5e42cf2393f444491ec/src/types.jl#L13 for the relevant field in `OptimizationOptions`, and https://github.com/JuliaOpt/Optim.jl/blob/ccc51d73621988265f77b5e42cf2393f444491ec/src/optimize.jl#L258 for the check in `optimize`.

**Comment by multidis** [comment]
Thank you, this is really helpful!

**Comment by pkofod** [comment]
Please report back if you have any issues with it.
