### ISSUE TITLE
Why does fminbox() require a DifferentiableFunction?

### ISSUE THREAD

**Issue by ahwillia** [JuliaOpt/Optim.jl#120]
I might be missing out on some key insight/knowledge here, but it seems like:

```julia
function fminbox{T<:FloatingPoint}(df::DifferentiableFunction, ... )
```

Could be changed to:

```julia
function fminbox{T<:FloatingPoint}(df::Function, ... )
```

The relevant line in the code is here: https://github.com/JuliaOpt/Optim.jl/blob/master/src/fminbox.jl#L108

Am I missing something? If so, maybe the `README` file should be updated to explain this restriction and why it exists.

**Comment by johnmyleswhite** [comment]
I would be happy to change the API, since I don't like the custom types.

But we do require that inputs have derivatives and we prefer analytic derivatives, which means that passing a single function in is not sufficient.

**Comment by ahwillia** [comment]
Thanks for the quick reply. What if I'm lazy and just want to apply something like Nelder-Mead to a problem with box constraints (and not worry about analytically calculating derivatives)? Also, what about objective functions like L1 norm that aren't differentiable everywhere (despite being pretty easy to solve)?

The [Nelder-Mead function](https://github.com/JuliaOpt/Optim.jl/blob/master/src/nelder_mead.jl#L42) doesn't require a `DifferentiableFunction` as input, so maybe making a box-constrained Nelder-mead function would be worthwhile?

**Comment by johnmyleswhite** [comment]
I'm not aware of work showing that Nelder-Mead behaves sensibly with box constraints. Got a literature citation you'd like to share so that we could implement it someday?

I would suspect many of the algorithms we're using probably don't behave properly on solving L1 norm problems.

I guess a more important question: are you using the `optimize` function? If not, why not? The package assumes you do everything via that function.

**Comment by IainNZ** [comment]
If you really do have a L1-norm+box-constrained problem, I'd suggest using linear programming, which is supported in a variety of ways in JuliaOpt (can provide more info if needed).

I don't know if box-constrained nelder-mead is a thing thats been well explored.

**Comment by ahwillia** [comment]
I was following the examples in this section of the `README`: https://github.com/JuliaOpt/Optim.jl#box-minimization

You're right that it seems like Nelder-Mead is better for unconstrained problems. My mistake -- I thought I had used it before via `scipy.optimize`. But it seems like they offer different algorithms for constrained minimization: http://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.minimize.html#scipy.optimize.minimize

@IainNZ -- I was just using L1 as a simple example. My particular problem is something closer to: `minimize abs(x^2 - 5)`

**Comment by IainNZ** [comment]
This is getting off-topic, but: is it convex? and, unrelated, you could use JuliaDiff stuff to automatically differentiate your objective, no extra effort on your part. Dimension of problem?

**Comment by ahwillia** [comment]
Essentially I have two sequences of Bernoulli variables. I want to come up with parameters such that the Jensen-Shannon divergence (a convex function) between the two equals a certain target value. Thus, the problem isn't convex (because I'm not looking to find the minimum distance). Here are plots of the objective function in two dimensions. In this case we have just have two Bernoulli variables with P and Q, but I want to extend this to higher dimensions.

![image](https://cloud.githubusercontent.com/assets/636625/7924395/a93adbc8-086f-11e5-8718-7892260f18f0.png)

**Comment by mlubin** [comment]
> What if I'm lazy and just want to apply something like Nelder-Mead

Laziness in most cases (i.e., when the objective function is written in pure Julia) isn't an excuse for not providing derivatives given the availability of the ``autodiff`` parameter for ``optimize``. This isn't implemented for ``fminbox`` yet though, so that would be a fair request. In the meantime, see @davidanthoff's [workaround](https://groups.google.com/forum/#!searchin/julia-opt/autodiff/julia-opt/UqsMDzvAAME/6bVn1DVWR98J).

**Comment by ahwillia** [comment]
@mlubin -- nice I will use that workaround.

I'm happy to close this issue, edit the title, or close and reopen a new one on implementing `autodiff` for `fminbox`.
