### ISSUE TITLE
Overloading Base.dot

### ISSUE THREAD

**Issue by kkylin** [JuliaOpt/Optim.jl#126]
Hi all,

I'm using Optim 0.4.1 with Julia 0.3.9, and came across this behavior:

julia> u=[1+2im,3-4im]
2-element Array{Complex{Int64},1}:
 1+2im
 3-4im

julia> dot(u,u)
30 + 0im

julia> using Optim

julia> dot(u,u)
-10 - 20im

This behavior seems to be a direct consequence of Optim overloading dot(), and can break code that works with complex data and uses dot(u,u) to compute norm^2.  Is this the intended behavior?

Other than this little thing, I've been a very happy user of Optim.jl.

Thanks!

Kevin

PS I'm guessing the fix to issue #98 also fixes this?

**Comment by mlubin** [comment]
This was fixed by #98. @johnmyleswhite, any reason not to tag?

**Comment by johnmyleswhite** [comment]
No, we should be safe to tag.

**Comment by mlubin** [comment]
Done
