### ISSUE TITLE
Is there interest in callback functions?

### ISSUE THREAD

**Issue by Evizero** [JuliaOpt/Optim.jl#130]
Hi! Awesome package! 

I wonder, was there a conscious decision to not support callback functions (performance reasons maybe)? If not, would there be interest? I know that there is the trace/history option and it might probably not be the most practical thing to do. However, I would really like them for what I want to implement for interface consistency among reasons 

I would of course be willing to spend the time to figure out a good way to allow for them (i.e. do the whole coding). I figured I ask first before coding away. Maybe that idea came up before and was rejected for some good reason that simpleton me is oblivious to

**Comment by mlubin** [comment]
What kind of callbacks are you looking for? Just informational callbacks or also callbacks to interact with the solution method (e.g., early termination)?

**Comment by Evizero** [comment]
Informational at the moment, but both in the long run. For example I want to be able to do a live plotting of the learning every k iterations. Also, if external code is given control I would be able to "step" through the optimization for demonstrations (to students). But It would be great if I could do early stopping after computing the validation error in the callback.

**Comment by Evizero** [comment]
Not I am not asking for anyone to spend time on this. I really just want to get a feel of what people are interested here. I have no issue with doing it myself and refactor my changes according to feedback. I just want to avoid doing work where it was clear that its not of interest to the package maintainers

**Comment by mlubin** [comment]
No objections here

**Comment by Evizero** [comment]
I think I can do it without breaking the interface using multiple dispatch. Essentially I would make the first parameter the callback and create a default callback for the current trace option. This would allow me to do the following additionally to the current interface

```Julia
res = optimize(f, [0.0, 0.0], break_every=100) do status
  # do stuff with status
end
```

**Comment by mlubin** [comment]
There are already multiple methods with a varying number of functions as inputs, not sure we can tack on another one without ambiguity. Why not a keyword argument to pass in the callback?

**Comment by Evizero** [comment]
Now I see what you mean in optimize.jl. My bad. I was looking at the algorithms themselves which just have the `DifferentiableFunction` and such. silly me. Yes keyword argument then
