### ISSUE TITLE
momentum gradient descent and mu

### ISSUE THREAD

**Issue by Evizero** [JuliaOpt/Optim.jl#132]
I've been wondering about something. `momentum_gradient_descent`, for example, has the momentum importance parameter `mu`. However, `optimize` does not support for a way to overwrite the default value. Is this on purpose? Wouldn’t it be feasible to provide an `args...` argument to propagate those special named arguments or am I missing something?

**Comment by johnmyleswhite** [comment]
The momentum gradient descent implementation is basically useless and should be removed from the codebase at some point.
