### ISSUE TITLE
Missing method in finite_difference_jacobian!

### ISSUE THREAD

**Issue by asprionj** [JuliaOpt/Optim.jl#133]
Hi, I'm new to Julia and just wanted to test its performance on some problem I'm currently playing with. It concerns nonlinear least-squares, so I wanted to use curve_fit() from the LsqFit package. However I get the following error connected to Optim.levenberg_marquardt():

ERROR: `finite_difference_jacobian!` has no method matching finite_difference_jacobian!(::Function, ::Array{Float64,1}, ::Array{Float64,2}, ::Array{Float64,2}, ::Symbol)
 in g at C:\Users\board\.julia\v0.3\Calculus\src\derivative.jl:23
 in levenberg_marquardt at C:\Users\board\.julia\v0.3\Optim\src\levenberg_marquardt.jl:52
 in lmfit at C:\Users\board\.julia\v0.3\LsqFit\src\curve_fit.jl:29
 in curve_fit at C:\Users\board\.julia\v0.3\LsqFit\src\curve_fit.jl:39
 in include at boot.jl:245
 in include_from_node1 at loading.jl:128

Let me know what additional information you need to figure out the problem. Thanks!

**Comment by mlubin** [comment]
Could you post a self-contained example which we can run to reproduce this error?

**Comment by asprionj** [comment]
Hi, found the problem. Apparently not all of my data (and return value of my function) were column vectors. Used vec() on everything, now it works. Thanks anyways!
