### ISSUE TITLE
least square optimization

### ISSUE THREAD

**Issue by matthieugomez** [JuliaOpt/Optim.jl#137]
There are several performance issues with the current levenberg marquardt implementation
- The functions given by the user should be f! and g! rather than f and g so that the method can avoid the creation of new arrays at each iteration.
- The creation of a matrix J'J is costly for high dimensional problems. `J'J` is a very large matrice (size equal to the number of parameters), and is not sparse in general, even though `J` may be. I have written an implementation of levenbarg marquardt for high dimensional problems  [here](https://github.com/matthieugomez/SparseFactorModels.jl/blob/master/src/utils/levenberg_marquardt.jl), which is similar (in spirit) to the one used in Google Ceres solver. I'd love to add it at some point.

These changes would require important changes in the API for least square. I can try to implement them, but I wanted to get some feedback first.

**Comment by blakejohnson** [comment]
I think the standard interface to most other solvers in Optim.jl is to provide `f` and `g!`. So, if we are going to change the API, we should probably be consistent with that. Also, LsqFit.jl is a significant user of `levenberg_marquardt`, so we'd need to coordinate the update.

**Comment by matthieugomez** [comment]
Contrary to the other solvers, we also need the user to also provide `fcur`, or at least its dimension, since this information is not available from `x0`.

**Comment by matthieugomez** [comment]
I have implemented [here](https://github.com/matthieugomez/SparseFactorModels.jl/tree/master/src/utils/lsoptimization)
- least square optimization using levenberg_marquardt
- least square optimization using dogleg

Both methods require to solve A'A x \ A' f(x) at each step. In  levenberg_marquardt, A is the contatenation of the jacobian and dia(J'J). In dogleg, A is just the jacobian.

This problem is solved differently depending on the type of A
- If A is a Matrix, by usual division
- if A is sparse (or is any type that implements multiplication), by conjugate gradient (more precisely [LSMR]  algorithm (http://web.stanford.edu/group/SOL/software/lsmr/) with Jacobi preconditioner).

It would be nice to add them here as a pull request at some point, so I welcome feedback.

**Comment by johnmyleswhite** [comment]
This sounds better suited for a custom package. We try to ensure that all the tools in this library reflect optimization solvers for generic functions.

**Comment by matthieugomez** [comment]
@blakejohnson I've written a repository with least squares minimization [here](https://github.com/matthieugomez/LeastSquares.jl). Compared to the optimization here
- beyond the  `levenberg_marquardt`, there is also a `dogleg` method (generally more efficient)
- it acts on sparse jacobians (through sparse factorization or iterative method) or any object defined by `A_mul_B` method (through iterative method)
- it avoids any allocation within iterations
Please open an issue there if you have comments!
