### ISSUE TITLE
Naming conventions and APIs - breaking changes?

### ISSUE THREAD

**Issue by pkofod** [JuliaOpt/Optim.jl#140]
As discussed in #139 we might want to make a little push on some of the features of Optim. One such thing is a proper API for accessing convergence information and optimization output in general. @johnmyleswhite already has a branch with a lot of functions added.

One thing that has been brought up (in #76 for example) is the improper use of the term minimum in this package. If we do go ahead and change that, what would be the best way to do it? Some peoples code might depend directly on the field name (which is exactly why we need a proper API so we can use the deprecation tools in the future for such changes). I guess we simply make a breaking change? Or are there deprecation tools for this sort of thing? We could just copy the contents of the .minimizer field to a .minimum, such that old programs still work, but this seems awkward.

Edit: another way is of course to add only the functions for extracting information in the first round, and the change the internal names when people have had a chance to change their code to using the new function based API.

**Comment by mlubin** [comment]
Unfortunately there's no way to deprecate field access. My vote is to just break things (with notice to julia-opt list and documentation in the README) if we have a significant improvement to make. The package isn't mature enough to be held back by legacy code.

**Comment by johnmyleswhite** [comment]
I'm ok with breaking things, although it seems better to me to start by creating a formal API before breaking the informal API (i.e. the direct field access strategy).

**Comment by johnmyleswhite** [comment]
How willing are we to break things? I think we could simplify the code considerably if we made the optimization methods into abstract types and used type dispatch to replace the big manual keyword dispatch that's happening in `optimize`.

**Comment by mlubin** [comment]
No objections here

**Comment by pkofod** [comment]
Fine with me

**Comment by Ken-B** [comment]
With another package I'm also replacing manual dispatch to type dispatch, but I wonder whether it's best to use abstract types for this or type instances? 

The manual seems to [suggest](http://docs.julialang.org/en/release-0.4/manual/style-guide/#avoid-confusion-about-whether-something-is-an-instance-or-a-type) type instances. Any reason you'd prefer an abstract type for each optimization method instead of a type instance?

Apologies if I seem to be hijacking the issue, but I thought this comment might be useful here before starting the new implementation.

**Comment by oxinabox** [comment]
GadFly uses both type instances and abstract types, where the type instances (when instantiated) hold the special method parameters. (sometimes)

**Comment by pkofod** [comment]
The questions have been answered.
