### ISSUE TITLE
Nelder-Mead failure for sine function optimization

### ISSUE THREAD

**Issue by Vgrunert** [JuliaOpt/Optim.jl#142]
Hi,

I would like to get the following topic to your attention:

http://stats.stackexchange.com/questions/176350/non-linear-least-squares-sine-frequency-estimation-in-julia

In short: the Optim Nelder-Mead implementation fails for estimation of frequencies of a sine function. Using the JuMP/NLopt LN_NELDERMEAD implementation works.

**Comment by mlubin** [comment]
The nelder-mead algorithm has poor convergences guarantees in general. It's not surprising that it wouldn't give a good answer for a nonconvex problem.

**Comment by Vgrunert** [comment]
Well but the other ones failed completly...

**Comment by mlubin** [comment]
Try a derivative-based method

**Comment by Vgrunert** [comment]
They all result in failures or set the sine related parameter to 0
