### ISSUE TITLE
Significant figures in OptimizationState show

### ISSUE THREAD

**Issue by micahjsmith** [JuliaOpt/Optim.jl#150]
Currently, an `OptimizationState` object is shown as follows:
```
function Base.show(io::IO, t::OptimizationState)
    @printf io "%6d   %14e   %14e\n" t.iteration t.value t.gradnorm
```

It might be helpful to provide more significant figures for the `value` and `gradnorm` fields. The default `ftol` and `grtol` values are `1e-32` and `1e-8`, respectively. Given this, I think 8 decimal places (`"%14.8e"`) would be a reasonable minimum format. (By default, 6 decimal places are used.) Otherwise, it is hard to tell, after a certain point, what progress is being made to convergence. One could even conceive of modifying this format based on the actual tolerances used.

**Comment by pkofod** [comment]
I generally agree with your observations, but using the tolerances would mean that they should be accessible to `show`. Would you propose to add the tolerances to all instances of `OptimizationState`? That seems a bit odd to me.

**Comment by micahjsmith** [comment]
I agree that it seems odd to add tolerances to `OptimizationState`, which are otherwise unrelated. So perhaps increase to `%14.8e` format?

**Comment by pkofod** [comment]
Seems like a good alternative, as a gradient tolerance of 1e-8 is pretty standard. There may be an easy (more general) fix, although I must admit I haven't really looked too much into this since last time. Maybe something like the Formatting package can be used.

**Comment by pkofod** [comment]
Actually, looking at #201 why is this necessary? Looking at the output, I am now confused about your original comment. Since we're using `%e`, the `-xx` (for example `-09`) term should allow for very small changes. Can you provide an example I can run to see the problem?

**Comment by pkofod** [comment]
I'm closing this, as I don't agree that you cannot see small changes. Please reopen with an example if you disagree.
