### ISSUE TITLE
Linesearch output in teh/constrained branch

### ISSUE THREAD

**Issue by multidis** [JuliaOpt/Optim.jl#151]
I am using `fminbox` with `cg` optimizer from `teh/constrained` branch of the package. Overall, the results seem better vs. the `master` code (just a semi-quantitative observation), probably after [recent](https://github.com/JuliaOpt/Optim.jl/pull/144) linesearch improvements.

The issue is that one in a while (i.e. once every 1000 or so optimization runs) the output is printed

    lsr = Optim.LineSearchResults{Float64}(... values ...)

and I am not sure what causes it. The closest was [L257](https://github.com/JuliaOpt/Optim.jl/blob/teh/constrained/src/linesearch/hz_linesearch.jl#L257) but there is no `c = ` output.

@timholy any experience with this output? My optimizations run via `pmap` as parts of larger try-catch chunks and this output sometimes comes from one of the worker-cores, thus it was not straightforward to reproduce. Nothing else is printed in the shell except for the `lsr` value.

**Comment by timholy** [comment]
Nope. That's the output you'd get from `@show lsr`, but by grep the only example I see of that in the code is right above an error. Well, maybe your try/catch is obscuring the error?

**Comment by multidis** [comment]
Nothing obvious in my try/catch to eat up part of the output but leave the other part, but I'll keep observing.

**Comment by timholy** [comment]
If you can run in a single process, sometimes that's easier for debugging.

**Comment by multidis** [comment]
This output appears to be a result of how `pmap` handles exceptions:

https://github.com/JuliaLang/julia/issues/7808
https://github.com/JuliaLang/julia/issues/12908

Not an issue on the `Optim.jl` side.
