### ISSUE TITLE
Simplify "Basic API Introduction"

### ISSUE THREAD

**Issue by benjohnbarnes** [JuliaOpt/Optim.jl#159]
A pedagogical point regarding README.md

In "Basic API Introduction", `rosenbrock`, `gradient` & `hessian` functions are defined. `gradient` and `hessian` are not necessary for the basic API usage example: `optimize(rosenbrock, [0.0, 0.0])`. 

Having the gradient and hessian defined early in the document may lead readers to believe they will be needed for even the most basic API usage. They did me, at least, until I read more :-)

The gradient is used later when discussing L-BFGS. I'd suggest defining the necessary functions at this point, rather than earlier on, and discussing how they will help the search to converge more rapidly.

**Comment by timholy** [comment]
Hi @benjohnbarnes, it's quite easy for anyone to edit the README: just click on the file in the list of files, then click on the little pencil icon. Make your changes and then hit "submit." Someone will review your changes before they get merged.

**Comment by benjohnbarnes** [comment]
Thanks, I'll have a bash at that.

**Comment by pkofod** [comment]
@benjohnbarnes note that we are currently changing the API. After #149 is merged would be good time to do this change, as I agree with you that it is not currently optimally presented.

**Comment by pkofod** [comment]
I've changed this in a PR to the branch that is to be merged in #149 so merging that should fix this.

**Comment by benjohnbarnes** [comment]
Thank you @pkofod, nice one.

**Comment by pkofod** [comment]
It should be fine now, right? Is that how you imagined it?

**Comment by benjohnbarnes** [comment]
Yes! It's much better like this; a lot clearer!

**Comment by pkofod** [comment]
Then I'll close this issue, and thank you for pointing it out.
