### ISSUE TITLE
It would be magically cool to pass in non vector types.

### ISSUE THREAD

**Issue by benjohnbarnes** [JuliaOpt/Optim.jl#160]
The `optimize` function takes an initial guess in the form of a vector, and the objective function that must take that vector.

My objective function might prefer to take a parameter that is _not_ a vector.

For example, it might want to take a tuple of 2 arguments: a 3x3 matrix & and a 3 vector. It'd be lovely if `optimize` would let me provide an objective function that takes that form, and also pass in an initial estimate in that is in that form.

I'm not sure how gradients would then be specified!

**Comment by johnmyleswhite** [comment]
This seems too vague to be made to work without enormous effort.

**Comment by tkelman** [comment]
This indexing transformation is a large part of what modeling language layers like JuMP or Convex.jl are designed to do for you. Optim is implementing the algorithms, not the user presentation with parameter names and shapes that are convenient to any specific problem.

**Comment by benjohnbarnes** [comment]
@tkelman Thanks you, Convex.jl looks interesting. I agree @johnmyleswhite this would require a lot of effort.
