### ISSUE TITLE
OptimExamples.jl

### ISSUE THREAD

**Issue by pkofod** [JuliaOpt/Optim.jl#170]
Based on other packages (`Plots.jl` for example,) in the Julia ecosystem, I find it nice to separate examples out into separate packages. What would people think about an OptimExamples.jl package? First step would simply be to transfer `src/problems` and from there we can add more examples. 

I've created https://github.com/pkofod/OptimExamples.jl and will demonstrate what I mean over the weekend, but feedback is encouraged.

**Comment by mlubin** [comment]
We could also use some Optim examples at https://github.com/JuliaOpt/juliaopt-notebooks.

**Comment by Evizero** [comment]
I think the main reason for `Plots.jl` to do it is because images take up significant amount of space that accumulates quickly when version-controlled by git.

What is the intend behind the separation? Do you aim to provide some functions that walk the user through the package?

**Comment by KristofferC** [comment]
A simple example folder with notebooks ought to work just as well IMHO.

**Comment by pkofod** [comment]
I see what you're saying. We can keep it in `Optim.jl`. I also see that since we're using them for the tests, it would be weird to move them. I'll make an `examples/` folder instead. @mlubin If I add the notebooks here at `Optim.jl` do you want it mirrored in `juliaopt-notebooks` or maybe just provide a link in `README.md`?

**Comment by mlubin** [comment]
I don't think mirroring is a great idea since it creates additional maintenance burden, but we should at least have links in one direction or the other.

**Comment by pkofod** [comment]
Regarding some of the comments above. I kind of wanted to add some visuals to some of the examples. Will this bloat the git history as per @Evizero s comment?

**Comment by Evizero** [comment]
Maybe those fit better into https://github.com/JuliaOpt/juliaopt-notebooks then? One could always link from the examples folder to there for "further information". Maybe but a REAMDE.md in the examples folder of Optim.jl that states this

**Comment by pkofod** [comment]
That sounds like a plan.

**Comment by Ayush-iitkgp** [comment]
I find Convex.jl's way of organizing examples pretty convenient for new users and also for someone who is willing to add more examples. 
We can create an examples/ folder in Optim.jl and add ipython-notebooks in it which can be hosted on  nbviewer very similar to Convex.jl (http://nbviewer.jupyter.org/github/JuliaOpt/Convex.jl/tree/master/examples/) 

I am willing to add add examples to Optim package demonstrating its usefulness.

**Comment by johnmyleswhite** [comment]
I think it would be good to start by adding examples outside of the package and then pulling them in later.

**Comment by ChrisRackauckas** [comment]
>A simple example folder with notebooks ought to work just as well IMHO.

No it doesn't after awhile. Notebooks tend to overwrite themselves with every update. This can bloat the Git history really fast as @Evizero said, and DifferentialEquations.jl had to move its notebooks out for this reason. I think adding it to https://github.com/JuliaOpt/juliaopt-notebooks is a better option because then it's isolated (if that repo ever grows too big, its history can be wiped. This can't happen with registered packages). The notebook repo should better use the README to show what's in there, and a link to the repo should be added here: http://www.juliaopt.org/learning/ (I don't like the "many more")
