### ISSUE TITLE
Fminbox needs a small cleanup 

### ISSUE THREAD

**Issue by pkofod** [JuliaOpt/Optim.jl#179]
Lately, we've seen some API clean-up, which is great. I went to `Fminbox` to try to address #167, but the following didn't work.
```julia
using Optim
function rosenbrock(x)
	temp_f = zero(eltype(x))
	for i = 1:(length(x)-1)
		temp_f +=100*(x[i+1] - x[i]^2)^2 + (x[i] - 1)^2
	end
	return temp_f
end
# rosenbrock(x) = sum(100*(x[i+1] - x[i]^2)^2 + (x[i] - 1)^2 for i = 1:length(x)-1) 
res = optimize(Optim.DifferentiableFunction(rosenbrock), zeros(2), fill(-10., 2), fill(10., 2), method = Fminbox())
``` 
Which I would have thought would work. I guess we just need to add the same `optimize` methods as for the other methods (the keyword version in `method.jl` and the `OptimizationOptions` in `optimize.jl`).

However, as said above, I wanted to address #167, so I wanted to change `f_minimum` to `df.f(minimizer)`, such that we do not return the function value plus the barrier function. After all, the user wants to minimize the original function, so it makes sense to return what minimal value could be obtained. Looking at the returned `MultivariateOptimizationResults`, I noticed that it was `results`. Now first of all, `results` is declared in a `local results` statement, which I think should be `results = MultivariateOptimizationResults[]`, as we later use `append!` to add each `ConjugateGradient()` result to `results`. However, it doesn't get appended (did the behaviour of `append!` change over the years?) , it just gets overwritten, and `results` ends up given the wrong output:
```julia
julia> res
Results of Optimization Algorithm
 * Algorithm: Conjugate Gradient
 * Starting Point: [0.0,0.0]
 * Minimum: [0.9999999925183246,0.9999999850361568]
 * Value of Function at Minimum: -0.000000
 * Iterations: 3
 * Convergence: true
   * |x - x'| < 2.2e-16: false
   * |f(x) - f(x')| / |f(x)| < 1.5e-08: true
   * |g(x)| < 1.5e-08: true
   * Exceeded Maximum Number of Iterations: false
 * Objective Function Calls: 16
 * Gradient Call: 13
```

where in reality, these function and gradient calls are wildly misleading, as the output should probably rather be some kind of summary of the output below
```julia
julia> res
Results of Optimization Algorithm
** Major iteration 1
 * Algorithm: Conjugate Gradient
 * Starting Point: [0.9998482906341932,0.9996961095222481]
 * Minimum: [0.9998482906341932,0.9996961095222481]
 * Value of Function at Minimum: -0.045951
 * Iterations: 24
 * Convergence: true
   * |x - x'| < 2.2e-16: false
   * |f(x) - f(x')| / |f(x)| < 1.5e-08: true
   * |g(x)| < 1.5e-08: false
   * Exceeded Maximum Number of Iterations: false
 * Objective Function Calls: 91
 * Gradient Call: 67

** Major iteration 2
 * Algorithm: Conjugate Gradient
 * Starting Point: [1.0000024683396427,1.000004968799324]
 * Minimum: [1.0000024683396427,1.000004968799324]
 * Value of Function at Minimum: -0.000046
 * Iterations: 3
 * Convergence: true
   * |x - x'| < 2.2e-16: false
   * |f(x) - f(x')| / |f(x)| < 1.5e-08: true
   * |g(x)| < 1.5e-08: false
   * Exceeded Maximum Number of Iterations: false
 * Objective Function Calls: 12
 * Gradient Call: 9

** Major iteration 3
 * Algorithm: Conjugate Gradient
 * Starting Point: [0.9999999925183246,0.9999999850361568]
 * Minimum: [0.9999999925183246,0.9999999850361568]
 * Value of Function at Minimum: -0.000000
 * Iterations: 3
 * Convergence: true
   * |x - x'| < 2.2e-16: false
   * |f(x) - f(x')| / |f(x)| < 1.5e-08: true
   * |g(x)| < 1.5e-08: true
   * Exceeded Maximum Number of Iterations: false
 * Objective Function Calls: 16
 * Gradient Call: 13
```

I will try to address these issues in a PR asap.

**Comment by pkofod** [comment]
Also, that while loop can only break if `converged` is eventually true - not good :)

**Comment by timholy** [comment]
`fminbox` is probably pretty suboptimal. I guess one could either try to fix it, or replace it via a general framework for constrained optimization. The latter is obviously harder, but perhaps more fruitful in the long run. (Sorry I haven't had time to push this over the finish line.)

**Comment by pkofod** [comment]
It is probably suboptimal, I just noticed some superficial things while "fixing" the returned minimum. Those are in #180 except for adapting the new API completely.

Truth be told, these things probably weren't noticed, because few people actually use `Fminbox()`. Doesn't mean we should let the :bug:s stay :)

**Comment by multidis** [comment]
I am confused with [this](https://github.com/JuliaOpt/Optim.jl/pull/180) now: there is the `iterations` limit passed to the optimizer:
https://github.com/JuliaOpt/Optim.jl/blob/pkm/f_minimum/src/fminbox.jl#L180
https://github.com/JuliaOpt/Optim.jl/blob/teh/constrained/src/fminbox.jl#L172

and now the same limit is applied to steps of the while loop? Those seem to be two different levels of iteration. I do think some limit is needed for the while loop as well, but a separate one; related to:
https://github.com/JuliaOpt/Optim.jl/issues/117

**Comment by pkofod** [comment]
@multidis I see what you're saying, but a time limit is really a separate PR imo. However, I will add two set of options instead of the current one. One for the major and one for the minor iterations. Are you using Fminbox a lot?

**Comment by multidis** [comment]
Two optional parameters seem appropriate: one for the step limit of the underlying optimizer and the other one for converging with the barrier function.

I do use `fminbox` a lot, with `cg` optimizer, primarily for refining the minimum after a global search. Following @johnmyleswhite suggestion I have been using @timholy 's `constrained` branch only for now.

**Comment by pkofod** [comment]
> Two optional parameters seem appropriate: one for the step limit of the underlying optimizer and the other one for converging with the barrier function.

I am not sure what you mean here. Let me also be frank: this is not my speciality, I just figured I'd fix some of the oddities of the current implementation.

**Comment by multidis** [comment]
Well, I was not precise in saying that, there is actually only one optional parameter `iterations` and the other limit I meant is passed to the underlying optimizer (via `optimizer_o`) at each call within the while-loop. At least that is the way your [PR](https://github.com/JuliaOpt/Optim.jl/pull/180) appears.

> Let me also be frank: this is not my speciality

Same here, I just hope that at some not very distant future time the constrained-branch is merged and we all live happily with the new API.

**Comment by pkofod** [comment]
Some of the changes have been implemented. The new API is not really functioning, but I think the whole constrained optimization needs a more general overhaul, so I'm not going to go too much into it for now. I think a separate discussion should be opened when we eventually get reach that point.
