### ISSUE TITLE
UndefVarError for optimization algorithms?

### ISSUE THREAD

**Issue by mw8** [JuliaOpt/Optim.jl#183]
I may be doing something stupid, but when I run the following code in Julia v0.4.5

    using Optim
    function f(x::Vector)
        return (1.0 - x[1])^2 + 100.0 * (x[2] - x[1]^2)^2
    end
    optimize(f, [0.0, 0.0], NelderMead())

I get the following error:

    ERROR: UndefVarError: NelderMead not defined

but when I change the last line to:

    optimize(f, [0.0, 0.0])

I get correct results. Perhaps the optimization algorithm names are not being exported correctly? It's also possible I did not import them correctly.

**Comment by pkofod** [comment]
This is because you are looking at the development version readme. Have a look at #176

**Comment by mw8** [comment]
Oh, I should have checked the previously closed issues. Many thanks.

**Comment by pkofod** [comment]
No problem, I'm adding a notice to the readme later. It might not be obvious to everyone. Hope you figure it out. I would suggest checking out the newest version instead of learning the old syntax.
