### ISSUE TITLE
Tagging releases

### ISSUE THREAD

**Issue by pkofod** [JuliaOpt/Optim.jl#184]
Do we have any type of precedent or rules for tagging releases? I think the current master is getting quite far away from the latest version tagged at metadata.jl, and it might soon be time to make the changes official to avoid repeated issues that are already fixed. I'm not saying now is the time, there might still be some things we want merged before a version bump. We can also just add a "if you want to use the latest features, use `Pkg.checkout("Optim")` to checkout the current master` at the top of the readme.

**Comment by Ayush-iitkgp** [comment]
I think we should add Pkg.checkout("Optim") at the top of README as there have been many instances of first time users reporting "UndefVarError".

**Comment by pkofod** [comment]
I intend to do that later, my computer was just out of order earlier.

**Comment by mlubin** [comment]
Feel free to tag whenever you feel it's ready. I think it deserves an announcement to julia-opt and julia-users summarizing the changes.

**Comment by pkofod** [comment]
Thanks, that answers it.
