### ISSUE TITLE
Unexplained `break` in cg.jl

### ISSUE THREAD

**Issue by cortner** [JuliaOpt/Optim.jl#209]
While working on a  different edit, I ran into this piece of code in `cg.jl`, L.175...:

```
        # Reset the search direction if it becomes corrupted
        dphi0 = vecdot(gr, s)
        if dphi0 >= 0
            @simd for i in 1:n
                @inbounds s[i] = -gr[i]
            end
            dphi0 = vecdot(gr, s)
            if dphi0 < 0
                break
            end
        end
```

My question is on the  `if dphi0 < 0; break`.  Should this break the cg-loop if after reset the search direction is still not downhill? In that case, shouldn't it read   `if dphi0 >= 0; break` ? As it stands,  if `gr` is not zero, then `dphi0 = vecdot(gr, s)` will *always* be negative.

P.S.:
 `s[i] = -gr[i]` should be `s[i] = -pgr[i]` which comes with a new pull-request I am preparing. I can then also submit the ` if dphi0 < 0` fix (provided I am correct about it).

**Comment by cortner** [comment]
Just to flag this one more time: I didn't include this change in the pull-request I mention above because I was waiting for somebody to double-check it.

**Comment by pkofod** [comment]
Ill look into it, but I'm moving atm so I'm not at my pc too much. Maybe see what hz did to compare

**Comment by pkofod** [comment]
But I do agree it looks very strange in the context of the previous calculations. I would just prefer some sort of reference if it is easily available. I believe everything should be explained in their paper. Is the code for their implementation gpl'ed ? Then you probably shouldn't read their code

**Comment by cortner** [comment]
Couldn't find anything in the paper - HZ claim that their method doesn't need restart. Instead they do restart every n (some parameter?) iterations.  I suggest that the `@simd` loop resets the search direction to `s = - P \ g` (in master) and that this should be followed by a test whether `s` is still a descent direction, if not then the one should break. Thus, the test `if dphi0 < 0` should actually be `if dphi0 >= 0`. I suggest to change this.

**Comment by timholy** [comment]
Sorry I didn't notice this before (most messages get about 0.25s of consideration, sorry).

HZ's implementation is GPL, so be careful about looking at their implementation. 

That looks like a typo (probably mine?) and bug: should be `dphi >= 0` if it's relevant at all.

**Comment by cortner** [comment]
Patrick, do you want to just go ahead and make the change?

**Comment by pkofod** [comment]
Sure, I can do it.

**Comment by cortner** [comment]
I would have done it but I think you are quicker making the Chang than handling a PR
