### ISSUE TITLE
What is the history of history?

### ISSUE THREAD

**Issue by pkofod** [JuliaOpt/Optim.jl#213]
What is the history of adding `history.jl`? It doesn't seem to be used. @johnmyleswhite do you remember? I know it is 3 years ago :) If there no reason, I'm removing it.

**Comment by johnmyleswhite** [comment]
You can remove that. It was supposed to be a template for a function I planned to write to store traces, but I never worked on it.

**Comment by pkofod** [comment]
Cool, thanks.
