### ISSUE TITLE
Limiting search space

### ISSUE THREAD

**Issue by abieler** [JuliaOpt/Optim.jl#221]
I usually have limited search spaces for optimization problems.
What I do with algorithms that do not support this is just a simple coordinate transformation with help of  `tanh()`. Say limits are given by `xmin` and `xmax`. Then:

```julia
dx = xmax - xmin
xcenter = xmin + dx/2
th = tanh((x - xcenter) / dx)
x_scaled = xcenter + dx * th
```
Which asymptotically limits `x` to `xmin` and `xmax`.
Is this worth implementing in a general way into Optim? Or mentioning in the manual?

**Comment by mlubin** [comment]
This can be a pretty bad idea for gradient based methods since it can destroy important structure like convexity. I don't think we should be making this easier to do... the right fix is to use algorithms which are aware of the bound constraints.

**Comment by johnmyleswhite** [comment]
Agree with @mlubin: we should document constraints after they're improved and make clear that people should work with those instead.

**Comment by pkofod** [comment]
I'm going to close this. There are already issues for the constrained branch, and we're not going to go down this route.
