### ISSUE TITLE
bug in powell_hessian! function

### ISSUE THREAD

**Issue by amroamroamro** [JuliaOpt/Optim.jl#226]
There is a small bug in the hessian calculation of the Powell function (`src/problems/unconstrained.jl`).

Both `storage[1,4]` and `storage[4,1]` should be `-120.0 * (x[1] - x[4])^2` not `0.0`.

**Comment by pkofod** [comment]
That is correct. Do you want to make a PR? There's also a typo in the description `### Difficuly since the hessian is singular at the optimum` the y should be a t :)

**Comment by amroamroamro** [comment]
@pkofod PR sent

**Comment by pkofod** [comment]
closed by #227
