### ISSUE TITLE
Use ForwardDiff instead of DualNumbers for AD

### ISSUE THREAD

**Issue by KristofferC** [JuliaOpt/Optim.jl#228]
ForwardDiff should have better performance and also support computing Hessians. I recently upgraded NLsolve to use the new ForwardDiff (https://github.com/EconForge/NLsolve.jl/pull/54) so I don't mind doing it myself here but with JuliaCon + vacation afterwards it might take a bit. 

Any opinions?

**Comment by pkofod** [comment]
Sounds good to me. Let me know if you start working on it, but if you don't I will do it myself when I get time to do it.
