### ISSUE TITLE
simultaneous evaluation of hessian

### ISSUE THREAD

**Issue by Linusnie** [JuliaOpt/Optim.jl#230]
I have an objective function whose value, gradient and Hessian can be naturally computed through a common function. As far as I can tell there is currently no support for taking advantage of such structure.

I think it would be appropriate to add a field similar to `fg!` in `TwiceDifferentiableFunction` that also updates the hessian, i.e. for example
```
function fgh!(x,g,h) 
    <computation of f_x, g_x, h_x>
    g,h = g_x, h_x
    return f_x
end
```
Since newton() always computes gradients and hessians in succession anyway this should only require a slight modification.

**Comment by mlubin** [comment]
You can use a closure and your own data structure to simulate this, just check if the evaluation point is new, and if so calculate all at once, store it, and return it from the corresponding callbacks as needed. I don't think we need to go in and change Optim.

**Comment by pkofod** [comment]
I think @mlubin's suggestion is better than going further down the `fg!` road. It is actually mentioned under Tips and Tricks in the upcoming updated documentation #224 (see http://pkofod.github.io/OptimDoc.jl/latest/user/tipsandtricks/, second section), I just havn't merged it yet. I am kind of looking for a good example. Maybe your problem can be mentioned?

**Comment by Linusnie** [comment]
Thanks for the tips! I will have a look through the documentation then. 

As for the specific problem I am fitting a linear model of the kind: 

> `y(t)+a*y(t-1) = b*u(t-1) + e(t) + c*e(t-1) `

to some input/output data u(t)/y(t) using optimization. To compute the gradient/hessian of the estimation error with respect to the parameters `a,b,c` you need to integrate the system so there is a common for loop to value function, gradient and Hessian. I can send you some example code once I'm done if you'd like.

**Comment by pkofod** [comment]
Closing this, as there is really nothing left here I think. The docs are online now.
