### ISSUE TITLE
LBFGS fails locally

### ISSUE THREAD

**Issue by KristofferC** [JuliaOpt/Optim.jl#231]
If I run the LBFGS test in the terminal it passes:

```jl

   julia> results = Optim.optimize(d, initial_x, method=LBFGS())
Results of Optimization Algorithm
 * Algorithm: L-BFGS
 * Starting Point: [10.0,10.0]
 * Minimizer: [61.800000000000004,17.0]
 * Minimum: 0.000000e+00
 * Iterations: 2
 * Convergence: true
   * |x - x'| < 1.0e-32: false
   * |f(x) - f(x')| / |f(x)| < 1.0e-32: false
   * |g(x)| < 1.0e-08: true
   * Reached Maximum Number of Iterations: false
 * Objective Function Calls: 9
 * Gradient Calls: 9
```

However, if I run Pkg.test it fails:

```jl
Results of Optimization Algorithm
 * Algorithm: L-BFGS
 * Starting Point: [10.0,10.0]
 * Minimizer: [-8.849379004077524e-5,10.0]
 * Minimum: 6.132692e-17
 * Iterations: 7
 * Convergence: true
   * |x - x'| < 1.0e-32: false
   * |f(x) - f(x')| / |f(x)| < 1.0e-32: false
   * |g(x)| < 1.0e-08: true
   * Reached Maximum Number of Iterations: false
 * Objective Function Calls: 32
 * Gradient Calls: 32

 Test Failed
  Expression: norm(Optim.minimizer(results) - [309.0 / 5.0,17.0]) < 0.01
   Evaluated: 62.19526459337784 < 0.01
```

It seems to converge to some other very shallow region..?

**Comment by pkofod** [comment]
Is it just the test you're running directly? Seems odd that it hasn't failed on travis then...

**Comment by KristofferC** [comment]
I copy paste the test file into the REPL, it works. I run Pkg.test("Optim") and it fails on this test. I agree it is weird...

**Comment by pkofod** [comment]
That is so weird. It works locally here, both copy+paste and `Pkg.test("Optim")`. Also, the travis run on the latest PR also succeeded ? https://travis-ci.org/JuliaOpt/Optim.jl/builds/138872717

**Comment by pkofod** [comment]
This is stable and nightly Julia by the way (although nightly Julia throws a million dep warnings :))

**Comment by KristofferC** [comment]
Now it works... wtf :/ :/

**Comment by pkofod** [comment]
What is really weird  is that there should be *nothing* random in this test so it should really be the exact same result across runs. And if you were using the same build of Julia (and dependencies)... I really don't get it :)
