### ISSUE TITLE
Documentation shows incorrect API

### ISSUE THREAD

**Issue by RedPointyJackson** [JuliaOpt/Optim.jl#232]
The README.md says that invocation is in the form

    optimize(f,init_param, function()

but the only accepted usage after doing `Pkg.add` is

    optimize(f,init_param, method=:function)

For example, `optimize(f,init_param,NelderMead())` throws an UndefVarError and `optimize(f,init_param,method=:nelder_mead)` works fine. Is this normal?

**Comment by Evizero** [comment]
curious. It looks like the last tagged version should already have the new API.

- Did you try `Pkg.update()` ?
- What is your Julia version?

**Comment by RedPointyJackson** [comment]
Doing a `Pkg.update()` did it, thank you. My julia version, if still interested, is 0.4.5
