### ISSUE TITLE
method_lookup not defined

### ISSUE THREAD

**Issue by bisraelsen** [JuliaOpt/Optim.jl#234]
Trying to run `optimize` and getting this error:

```
ERROR: LoadError: UndefVarError: method_lookup not defined
 in optimize at /home/user/.julia/v0.4/Optim/src/optimize.jl:91
```

I am running it through GaussianProcesses.jl. It was working fine and then stopped (within a few minutes).

**Comment by pkofod** [comment]
This is partially a mistake on our (my...) part, as https://github.com/JuliaOpt/Optim.jl/blob/b01425755c653ff8fe11cc1e3aa41b648331f6dd/src/deprecate.jl is not deleted for some reason, and partially a bug in GaussianProcesses, as a symbol shouldn't be used when calling `optimize`.

To understand you correctly, you didn't use `optimize` yourself, right? You just used it indirectly through `GaussianProcesses.jl`.

**Comment by bisraelsen** [comment]
Yes I used it indirectly through `GaussianProcesses.jl`. On further investigation I found that v0.2.1 of `GaussianProcesses.jl` (the one that gets installed when using Pkg.add()) uses `cg`, but the latest master branch uses `ConjugateGradient()`. So, I think I need to update to the latest build of `GaussianProcesses.jl`

Thanks for the quick response!

**Comment by pkofod** [comment]
For now (until they tag a new version) you can use the master, yes.  ( `Pkg.checkout("GaussianProcesses", "master")`)

No problem! Please do report any other issues you may come across!
