### ISSUE TITLE
Keywords...

### ISSUE THREAD

**Issue by pkofod** [JuliaOpt/Optim.jl#243]
I thought I had created an issue like this, but apparently I have not.

I was wondering what comments or objections people would have to removing the keywords, and forcing people to use the (dispatch based) `OptimizationOptions` for choosing options. I know it's a few more characters, but if you want to choose a solver and add a keyword, you have to write `method =` so really it isn't that many additional keystrokes. 

From a developer's point of view, I think it's much easier to ditch them, but if they're deemed very helpful, I guess they should stay. Would love to hear other people's opinion on this.

**Comment by anriseth** [comment]
This change will be good. I think it is useful to put all configuration of solvers in a options-objects, without too many other approaches to confuse users.

As a long-term inspiration, I like the approach the PETSc project has taken. You have full control of a wide range of solvers with special keywords via the same interface.

**Comment by pkofod** [comment]
> As a long-term inspiration, I like the approach the PETSc project has taken. You have full control of a wide range of solvers with special keywords via the same interface.

I'll take a look at PETSc. Thanks for your comment!

**Comment by cortner** [comment]
I like quick one-line calls of optimisers.  If the keyword arguments for the `optimise` calls go, then will it still be possible to do something similar but just with kwargs for OptimisationOptions?

**Comment by pkofod** [comment]
I found a way to clean up the code that handles the kwargs, so I let it stay for now, see #304. However, I did you ahead and make the `OptimizationOptions`->`Optim.Options` change. Deprecations should be in place. Kwargs might go later. Closing for now.
