### ISSUE TITLE
I get ERROR: LoadError: UndefVarError: input not defined when I try to run the .jl file from the julia terminal 

### ISSUE THREAD

**Issue by Rishabh-Raghunath** [JuliaOpt/Optim.jl#251]
Hello,
I am a beginner in the Julia language .. 
I get this error while I try to run ****.jl Julia program file from the terminal. However It works perfectly fine in the Juno IDE. This following is the error message I receive while trying to run the program from the Linux terminal:

ERROR: LoadError: UndefVarError: input not defined
 in legacy at /home/rishabh/Desktop/ProjectJulia/juliatest.jl:120
while loading /home/rishabh/Desktop/ProjectJulia/juliatest.jl, in expression starting on line 138

Thanks In advance

**Comment by KristofferC** [comment]
How is this related to Optim.jl? What is the code you are trying to run?

**Comment by johnmyleswhite** [comment]
Please submit usage questions to the julia-users mailing list.

**Comment by Rishabh-Raghunath** [comment]
Ohh.. I'm extremely Sorry .. I am new to github ..
Could You redirect me to the page if possible ?
Thanks

**Comment by Evizero** [comment]
welcome to julia!

This is the mailing list: https://groups.google.com/forum/#!forum/julia-users

**Comment by pkofod** [comment]
Please do come back if you run into problems using Optim.jl though! Closing this.
