### ISSUE TITLE
Should OptimizationTrace be an AbstractArray?

### ISSUE THREAD

**Issue by ahwillia** [JuliaOpt/Optim.jl#255]
I wanted to be able to gather the value of the objective function along the optimization path:

```julia
result = optimize(f, g!, x0; store_trace=true)
mytrace = Optim.trace(result)
objective_history = [ t.value for t in mytrace ]
```

But I get:

```
ERROR: MethodError: no method matching start(::Optim.OptimizationTrace)
```

All of these methods would be defined by default if we declare `OptimizationTrace` to be an `AbstractArray`.

Or do we even need a special type? Why not just have `Optim.trace(result)` return a `Array{OptimizationState,1}`? Pretty printing purposes?

**Also Related:** https://github.com/JuliaOpt/Optim.jl/pull/242

**Edit:**  I suppose the way to do this currently is:

```julia
objective_history = [ t.value for t in mytrace.states ]
```

**Comment by johnmyleswhite** [comment]
We should almost certainly do this, but what `AbstractArray` means is pretty vague. Your first example only really requires it implement an Iterator-like trait.

**Comment by pkofod** [comment]
I don't really have a good reason why we shouldn't ditch `OptimizationTrace{T}` in favour of `Vector{OptimizationState{T}}` where `T<:Optimizer`. Essentially, all we need for "pretty printing" is the last part. All instances of `OptimizationTrace` should simply be replaced by `Vector{OptimizationState}` I guess. :+1: from here

**Comment by ahwillia** [comment]
I'll open a PR later today to explore further.
