### ISSUE TITLE
Fminbox complaining about parameter eta?

### ISSUE THREAD

**Issue by anriseth** [JuliaOpt/Optim.jl#256]
I'm trying to use Fminbox with LBFGS, but it gives me the following error:
``` julia
ERROR: unrecognized keyword argument "eta"
 in optimize at /home/riseth/.julia/v0.4/Optim/src/fminbox.jl:188
```
The same issue arises with BFGS and GradientDescent, but ConjugateGradient seems to work.

Example:
```julia
using Optim, ForwardDiff
f(x) = x[1]^2
g!(x,out) = ForwardDiff.gradient!(out,f,x)
df = DifferentiableFunction(f,g!)
optimize(df, [2.0], [-5.0], [5.0], Fminbox(), optimizer=ConjugateGradient) # works
optimize(df, [2.0], [-5.0], [5.0], Fminbox(), optimizer=LBFGS) # fails
```

**Comment by pkofod** [comment]
What version of Optim? It works for me.

**Comment by anriseth** [comment]
Optim 0.4.5
ForwardDiff 0.2.2
Julia 0.4.7-pre+1

**Comment by pkofod** [comment]
I'm pretty sure the commit that allowed other optimizers than CG was part of Optim v0.5. Could you try updating Optim, or does it conflict with another package?

**Comment by anriseth** [comment]
That fixed it. I'm not sure what was causing the conflict.

**Comment by pkofod** [comment]
Great!
