### ISSUE TITLE
User-supplied gradient: Search direction is not a direction of descent (checked w/Matlab and gradient is correct)

### ISSUE THREAD

**Issue by Nosferican** [JuliaOpt/Optim.jl#258]
I am having issues supplying my gradient function for a least squares estimation. I am providing below the error message and the code to reproduce it (Julia Version 0.4.6, Optim 0.4.5, Win10, Jupyter) .

    using RDatasets
    using Optim
    iris = dataset("datasets", "iris")
    y = Vector(iris[:,1])
    n = length(y)
    X = hcat(ones(n),Matrix(iris[:,2:4]))
    function sqerror(β)
        return( ( sum( (y - X * β) .^ 2 ) ) / (2 * n) )
    end
    function g!(β::Vector, storage::Vector)
        storage = ( sum( (X * β - y) .* X, 1) / n )'
    end
    res = optimize(sqerror, zeros(4)) # W/o user-supplied gradient
    Optim.minimizer(res)
    gradient = ( sum( (X * zeros(4) - y) .* X, 1) / n )' # Same as with Matlab

    res = optimize(sqerror, g!, zeros(4)) # W/user-supplied gradient

    LoadError: Search direction is not a direction of descent;
    this error may indicate that user-provided derivatives are inaccurate.
    (dphia = 0.000000; dphib = 0.000000) while loading In[9],
    in expression starting on line 1 in error at error.jl:21

Thanks!

**Comment by pkofod** [comment]
It might be useful to actually use `g!` when comparing the gradient.

```julia

function g!(β::Vector, storage::Vector)
    storage[:] = ( sum( (X * β - y) .* X, 1) / n )'
end
```
works, do you see why? or 
```julia

g!(β::Vector, storage::Vector) = copy!(storage, ( sum( (X * β - y) .* X, 1) / n )')

**Comment by Nosferican** [comment]
Got it! So the assignment to the object does not update it and should be using either assignment to its elements or the `copy!` method to properly update the storage vector.

**Comment by KristofferC** [comment]
You are not the first to make this misstake: https://github.com/EconForge/NLsolve.jl/commit/460a59fab8db6bde87476a4125f0dd9a19247aeb
