### ISSUE TITLE
typecasts needed for BigFloat compatibility

### ISSUE THREAD

**Issue by andrewclausen** [JuliaOpt/Optim.jl#271]
The Optim.Brent() and Optim.GoldenSection() methods currently don't work with BigFloat.

The problem is very easy to fix: rel_tol and abs_tol need typecasts at the very end, inside the  UnivariateOptimizationResults() constructor.

**Comment by johnmyleswhite** [comment]
Any interesting in submitting a PR?

**Comment by pkofod** [comment]
Sounds great! Do you have a specific use case? Would love to include it as an example in the docs.

**Comment by andrewclausen** [comment]
I'm not sure what the best way to fix this is.  The definition of ``UnivariateOptimizationResults{T,M}`` involves several fields, including:

    minimizer::T
    minimum::Float64

I see two options:
1. Stick to the definition, and typecast everything into ``Float64`` (as per the definition).
2. Change the type definition to ``minimum::T``.

What was the original motivation for having both ``T`` and ``Float64``?

P.S. Sorry for the delay -- I had some heavy teaching commitments.

**Comment by johnmyleswhite** [comment]
I think the code has always had a mixture of generic constructs and implicit + explicit assumptions that all math is done using `Float64`. Cleaning this up is one of the things I'd be most interested in seeing done in the future.

**Comment by andrewclausen** [comment]
So, you think it's better to switch everything to ``T`` instead of ``Float64``?  Is this just a matter of search/replace everywhere, and maybe adding in some type-casts?

**Comment by pkofod** [comment]
> So, you think it's better to switch everything to T instead of Float64? Is this just a matter of search/replace everywhere, and maybe adding in some type-casts?

Yes, switching to "`T`", `zero(T)`, and so on is preferable if possible (and it probably is in many cases in numerical optimization).
