### ISSUE TITLE
Use Exitflag in Optimization Result

### ISSUE THREAD

**Issue by lindahua** [JuliaOpt/Optim.jl#28]
An optimization procedure may terminates for a variety of reasons:
- converged (changes are smaller than the tolerance)
- reached maximum number of iterations without convergence
- failed to find a good search direction
- numerical problems (e.g. the solution went unbounded, Inf or Nan occurred, etc)

Currently, the optimization functions returns ``OptimizationResults`` use a field ``converged`` to indicate the condition of exit. But this may not be able to provide accurate information if the procedure was terminated due to special reasons (e.g. numerical problems). 

Using a more informative exitflag (instead of only a boolean variable) also addresses the problems such as the one you encountered at (line 209 of l_bfgs.jl). In such cases, you can simply terminate the procedure, and use a proper exitflag to tell the caller what happened.

Here is a possible list of exit flags: http://www.mathworks.com/help/optim/ug/fmincon.html

However, I think using symbols instead of integers might make it more user-friendly.

**Comment by pkofod** [comment]
The current convergence information seems sufficient to me.

**Comment by johnmyleswhite** [comment]
Agreed.

**Comment by xiaohk** [comment]
Maybe one related issue #331

**Comment by xiaohk** [comment]
Maybe one related issue. #331
