### ISSUE TITLE
Remove `!` from `linesearch!` keyword in `Optimizer` objects

### ISSUE THREAD

**Issue by jiahao** [JuliaOpt/Optim.jl#285]
They are the cause of inscrutable whitespace-sensitive input errors:

```
result = optimize(rosenbrock, zeros(2), GradientDescent(linesearch!=hz_linesearch!
))

LoadError: UndefVarError: linesearch not defined
while loading In[10], in expression starting on line 1
```

It took students a long time to realize the problem could be fixed with

```
GradientDescent((linesearch!)=Optim.hz_linesearch!)
```

**Comment by KristofferC** [comment]
I have gotten confused by this as well. No point in having it in the keyword imorgon.

**Comment by pkofod** [comment]
> having it in the keyword imorgon.

or the day after that... :)

**Comment by KristofferC** [comment]
Swedish autocomplete hehe.

**Comment by jiahao** [comment]
@pkofod I agree that the whitespace convention you describe will avoid the problem of whitespace-sensitive parsing. However, I don't agree that it is a "solution". The convention in Julia is very much to provide keyword arguments without the whitespace; see, for example, [`test/statistics.jl`](https://github.com/JuliaLang/julia/blob/792ded802743830044198d2f525bded1f1c0bfb6/test/statistics.jl#L80) in Base.

**Comment by pkofod** [comment]
Okay, wasn't aware. Anyway, we shouldn't have an API that is easy to get wrong by missing a space. So convention or not, I vote for removing the !.

**Comment by pkofod** [comment]
Sooo... What is the best way to deprecate a character in a keyword? https://discourse.julialang.org/t/deprecating-usage-of-keywords/978

**Comment by KristofferC** [comment]
I posted an idea.

**Comment by pkofod** [comment]
In master due to #304 - I'll tag soon. Thanks for opening this @jiahao
