### ISSUE TITLE
Dispatch error on univariate optimization

### ISSUE THREAD

**Issue by Armavica** [JuliaOpt/Optim.jl#300]
* `optimize(cos, 0, 2pi)` works;
* `optimize(cos, 0, 2pi, Brent())` does not work (although `optimize(cos, 0.0, 2pi, Brent())` does);
* `optimize(cos, 0, 2pi, method = Brent())` works.

To my understanding, this happens because we have [`optimize{T <: AbstractFloat}(f::Function, lower::T, upper::T; kwargs...)`](https://github.com/JuliaOpt/Optim.jl/blob/master/src/optimize.jl#L286) and [`optimize(f::Function, lower::Real, upper::Real; kwargs...)`](https://github.com/JuliaOpt/Optim.jl/blob/master/src/optimize.jl#L316) in `optimize.jl` but the actual optimizer is defined in terms of [`optimize{T <: AbstractFloat}(f::Function, lower::T, upper::T, mo::Brent; kwargs...)`](https://github.com/JuliaOpt/Optim.jl/blob/master/src/brent.jl#L25) (and the equivalent for `GoldenSection`).

What is the best way to fix this problem?

**Comment by pkofod** [comment]
Thanks for the bug report. Wouldn't the addition of the following definition suffice?
```julia

function optimize(f::Function,
                  lower::Real,
                  upper::Real,
                  mo::Union{Brent, GoldenSection};
                  kwargs...)
    optimize(f,
             Float64(lower),
             Float64(upper),
             mo;
             kwargs...)
end
```

**Comment by Armavica** [comment]
It does, thank you for your assistance. I am preparing a PR. Should I include a note in `NEWS.md` as the contribution guide suggests?

**Comment by pkofod** [comment]
> It does, thank you for your assistance. I am preparing a PR. Should I include a note in NEWS.md as the contribution guide suggests?

sure, you can say a dispatch bug was fixed
