### ISSUE TITLE
Should OptimizationOptions be unexported and be called by Optim.Options?

### ISSUE THREAD

**Issue by pkofod** [JuliaOpt/Optim.jl#307]
Not exporting could be a help name space-wise, as it opens up for simply calling it `Options`. It is shorter than `OptimizationOptions` well, and with a `const opt = Optim` it can be even shorter (`opt.Options()`).

**Comment by anriseth** [comment]
Sounds sensible.
Could there be other types of "options" that would be added to Optim in the future? If so, there might be a clash.

**Comment by pkofod** [comment]
> Could there be other types of "options" that would be added to Optim in the future? If so, there might be a clash.

Possibly, can't think of one right now. This would probably be the "most common" Options constructor, so maybe any future Options will just have to be more specific?

**Comment by pkofod** [comment]
So actually we do have two examples: univariate optimization and Fminbox. Could do `1dOptions` (or 1D) and `BoxOptions`. The latter is probably going to be removed at some point anyway.

**Comment by pkofod** [comment]
closed by #304
