### ISSUE TITLE
ForwardDiff requirement

### ISSUE THREAD

**Issue by KristofferC** [JuliaOpt/Optim.jl#310]
Optim has a requirement of ForwardDiff to be version [0.2 - 0.3] and is now holding back ForwardDiff which is at 0.3.1.

**Comment by pkofod** [comment]
That's unfortunate. I'll see if we're tag-ready or what it would take (deprecations are not up to date I think).

**Comment by mlubin** [comment]
If there are no breaking changes we can retroactively bump the upper version bound on the existing tag.
