### ISSUE TITLE
getting lots of depreciation warnings fter Pkg.update()

### ISSUE THREAD

**Issue by zahachtah** [JuliaOpt/Optim.jl#316]
WARNING: MultivariateOptimizationResults(method,initial_x,minimizer,minimum,iterations,iteration_converged,x_converged,x_tol,f_converged,f_tol,g_converged,g_tol,trace,f_calls,g_calls) is deprecated, use MultivariateOptimizationResults(method,initial_x,minimizer,minimum,iterations,iteration_converged,x_converged,x_tol,f_converged,f_tol,g_converged,g_tol,trace,f_calls,g_calls,0) instead.
 in depwarn(::String, ::Symbol) at ./deprecated.jl:64
 in Optim.MultivariateOptimizationResults{T,N,M}(::String, ::Array{Float64,1}, ::Array{Float64,1}, ::Float64, ::Int64, ::Bool, ::Bool, ::Float64, ::Bool, ::Float64, ::Bool, ::Float64, ::Array{Optim.OptimizationState{LsqFit.LevenbergMarquardt},1}, ::Int64, ::Int64) at ./deprecated.jl:50
 in #levenberg_marquardt#1(::Float64, ::Float64, ::Int64, ::Float64, ::Bool, ::Array{Float64,1}, ::Array{Float64,1}, ::Function, ::#f_lm#3, ::#g_lm#4, ::Array{Float64,1}) at /Users/raukhur/.julia/v0.5/LsqFit/src/levenberg_marquardt.jl:169

Just FYI, maybe there is some WIP. appreciate all the work going into this pkg!

**Comment by pkofod** [comment]
You are using LsqFit.jl and after you updated Optim, you got the warning, right?

**Comment by zahachtah** [comment]
yes, I went into the code and added a 0 :-) assume its solved now and I can just checkout
