### ISSUE TITLE
How to configure converging criteria to satisfy all three thresholds? 

### ISSUE THREAD

**Issue by xiaohk** [JuliaOpt/Optim.jl#331]
I have provided the gradient function `g!`
```
julia> res = optimize(cost, g!, repeat([0.5], inner = 28))
Results of Optimization Algorithm
 * Algorithm: BFGS
 * Starting Point: [0.5,0.5, ...]
 * Minimizer: [-0.14819994541728726,-0.5200454965560813, ...]
 * Minimum: 4.003707e+00
 * Iterations: 3
 * Convergence: true
   * |x - x'| < 1.0e-32: false
   * |f(x) - f(x')| / |f(x)| < 1.0e-32: true
   * |g(x)| < 1.0e-08: false
   * Reached Maximum Number of Iterations: false
 * Objective Function Calls: 85
 * Gradient Calls: 85
```

I found that the minimizer is not quite accurate, because if I change the starting point, the minimizer would fluctuate significantly.

```
julia> res = optimize(cost, g!, repeat([2.1], inner = 28))
Results of Optimization Algorithm
 * Algorithm: BFGS
 * Starting Point: [2.1,2.1, ...]
 * Minimizer: [-3.748832659450549,1.2177682494128204, ...]
 * Minimum: 7.079591e+01
 * Iterations: 2
 * Convergence: true
   * |x - x'| < 1.0e-32: false
   * |f(x) - f(x')| / |f(x)| < 1.0e-32: true
   * |g(x)| < 1.0e-08: false
   * Reached Maximum Number of Iterations: false
 * Objective Function Calls: 78
 * Gradient Calls: 78
```

It only iterates twice, and only one of the tree convergence thresholds are satisfied. So I tried to force it to converge in the input vector, and converge in the gradient, by setting `f_tol` to a negative number (-10).

```
julia> res = optimize(cost, g!, repeat([0.5], inner = 28), Optim.Options(f_tol = -10))
Results of Optimization Algorithm
 * Algorithm: BFGS
 * Starting Point: [0.5,0.5, ...]
 * Minimizer: [-0.14819994541728726,-0.5200454965560813, ...]
 * Minimum: 4.003707e+00
 * Iterations: 3
 * Convergence: true
   * |x - x'| < 1.0e-32: false
   * |f(x) - f(x')| / |f(x)| < -1.0e+01: true
   * |g(x)| < 1.0e-08: false
   * Reached Maximum Number of Iterations: false
 * Objective Function Calls: 85
 * Gradient Calls: 85
```

However, the other two convergence thresholds are still not satisfied. Also, `|f(x) - f(x')| / |f(x)| < -1.0e+01: true` looks kind of strange (I am not sure how it is implemented to deal with negative number). 

My scales are quite small, so I want to have a more strict convergence criteria. I am wondering how to do that in Optm.jl?

**Comment by KristofferC** [comment]
What happens if you set `f_tol` to zero?

**Comment by xiaohk** [comment]
@KristofferC `|f(x) - f(x')| / |f(x)| < 0 ` is still satisfied after 3 iteration.

```
res = optimize(cost, g!, repeat([0.5], inner = 28), Optim.Options(f_tol = 0))
Results of Optimization Algorithm
 * Algorithm: BFGS
 * Starting Point: [0.5,0.5, ...]
 * Minimizer: [-0.14819994541728726,-0.5200454965560813, ...]
 * Minimum: 4.003707e+00
 * Iterations: 3
 * Convergence: true
   * |x - x'| < 1.0e-32: false
   * |f(x) - f(x')| / |f(x)| < 0.0e+00: true
   * |g(x)| < 1.0e-08: false
   * Reached Maximum Number of Iterations: false
 * Objective Function Calls: 85
 * Gradient Calls: 85
```

**Comment by KristofferC** [comment]
Looking at https://github.com/JuliaOpt/Optim.jl/blob/master/src/utilities/assess_convergence.jl#L18 it seems like the `nextfloat(f_x) >= f_x_previous` must be the one that gets satisfied.

**Comment by xiaohk** [comment]
@KristofferC So it means it gets stocked in local minima?

**Comment by KristofferC** [comment]
Yes, I think so.

**Comment by pkofod** [comment]
Would help to see your cost function. 85 gradient calls seems quite high for 3 major iterations. Have you tried other solvers?

**Comment by xiaohk** [comment]
@pkofod I am implementing logistic regression with regularization. `feature` in my code is a `118*28 matrix` containing the training examples. `Θ` is a `28*1 vector`, containing the parameters.
![image](https://cloud.githubusercontent.com/assets/15007159/21732551/9b211ade-d41f-11e6-98f8-7830616ce391.png)

```julia
function h(Θ, x)
    if size(x, 1) == 1
        return 1 / (1 + e ^ -(x * Θ)[1])
    else
        return result = map(z -> 1 / (1 + e ^ z), -(x * Θ))
    end
end

# Define the cost function. Regularization is used here. 
function cost(Θ)
    hypo = h(Θ, feature)
    m = size(feature, 1)
    pre = ((-value' * log(hypo) - (1 - value)' * log(1 - hypo)) / m)[1]
    # We do not regularize the first θ
    return pre + ((λ / (2 * m)) * sum(map(θ -> θ^2, Θ[2:end])))
end
```

I found someone solved the same problem using `scipy.optimize.minimize`.
![image](https://cloud.githubusercontent.com/assets/15007159/21732768/b41f69d6-d420-11e6-91ba-b4aebd220b88.png)
I am new to the computational optimize packages. Can you recommend me some other solvers?

**Comment by johnmyleswhite** [comment]
This seems like it's not an issue with Optim, but something you should discuss on Discourse.

Logistic regression with L2 regularization is a strongly convex problem with a single global optimum. If you're not finding that, it's quite likely that there's a bug in your implementation, although it's not impossible that there's a bug in Optim itself. I've solved a lot of logistic regression problems with Optim before, so I can certify that Optim as it stands can be used to solve this class of problems when implemented carefully.

**Comment by pkofod** [comment]
> I've solved a lot of logistic regression problems with Optim before, so I can certify that Optim as it stands can be used to solve this class of problems when implemented carefully.

I've never had problems solving logistic regression problems using Optim either, so while I cannot rule out that there's a bug in Optim, I suspect you might have a problem somewhere. Discourse or SO might be better suited for debugging this problem.

**Comment by pkofod** [comment]
Did you solve it @xiaohk ?

**Comment by xiaohk** [comment]
@pkofod Yeah, I have solved it. There are some errors in my implementation. Thank you so much! @pkofod @johnmyleswhite

**Comment by pkofod** [comment]
:+1:
