### ISSUE TITLE
Convergence when 'f_x >= f_x_previous`?

### ISSUE THREAD

**Issue by anriseth** [JuliaOpt/Optim.jl#339]
In `assess_convergence.jl`, there is a check:
```jl
if abs(state.f_x - state.f_x_previous) / (abs(state.f_x) + options.f_tol) < options.f_tol || nextfloat(state.f_x) >= state.f_x_previous
  f_converged = true
end
```
I don't like the part that checks `nextfloat(state.f_x) >= state.f_x_previous`. As it stands now, the optimization result falsely claims that the optimization converged due to `abs(f_x - f_x_previous) / abs(state.f_x)  < options.f_tol `

Can we either remove this, or separate it out as its own criterion (`allowincreasef_x = true/false`).

**Comment by KristofferC** [comment]
Introduced in https://github.com/JuliaOpt/Optim.jl/pull/80.

**Comment by anriseth** [comment]
This is especially an issue if one wants to run Newton without a linesearch (which I think we should allow)

**Comment by pkofod** [comment]
See Tim's constrained PR. He has some changes here. Does that do what you want?

Why is this an issue for newton?

**Comment by anriseth** [comment]
> See Tim's constrained PR. He has some changes here. Does that do what you want?
Okay, I'll have a look.

> Why is this an issue for newton?
Newton without LS can sometimes start by taking very long steps that increase the objective value, before converging from the new position. Omitting the LS is not very robust, but can be beneficial for the number of objective/gradient evaluations you do in total. I guess it's not restricted to Newton only.

**Comment by johnmyleswhite** [comment]
I just hit this and it was incredibly puzzling since I set `f_tol = 0.0` and still saw convergence in `f(x)`. Very strongly support changing this to a separate criterion.

**Comment by pkofod** [comment]
I will separate them out into two criteria. I hope I have time to do it tonight.

**Comment by pkofod** [comment]
But what was your case exactly @johnmyleswhite ? What solver? I mean, you probably want to stop if it cant decrease the objective in most cases. The current information communicated back to the user is just confusing right?

**Comment by johnmyleswhite** [comment]
This was for L-BFGS. Stopping is reasonable, but reporting convergence was confusing -- especially since it would literally print out the following:

```
Results of Optimization Algorithm
 * Algorithm: L-BFGS
 * Starting Point: [0.0,0.0,0.0,0.0]
 * Minimizer: [-0.21578786490387322,-0.21547142952943027, ...]
 * Minimum: 1.509442e+04
 * Iterations: 2
 * Convergence: true
   * |x - x'| < 1.0e-32: false
   * |f(x) - f(x')| / |f(x)| < 0.0e+00: true
   * |g(x)| < 1.0e-08: false
   * Reached Maximum Number of Iterations: false
 * Objective Function Calls: 82
 * Gradient Calls: 82
```

**Comment by johnmyleswhite** [comment]
Seeing anything that says `* |f(x) - f(x')| / |f(x)| < 0.0e+00: true` was making me panic that I had a bug in my code.

**Comment by pkofod** [comment]
It'll go as soon as I'm at a PC

**Comment by johnmyleswhite** [comment]
FWIW, I don't think this is a rush. Just a good change to make eventually.

**Comment by pkofod** [comment]
> FWIW, I don't think this is a rush. Just a good change to make eventually.

Yeah, it's just that if I don't fix it now, I'll just forget it ;)

**Comment by pkofod** [comment]
I'll fix it one of these days. I've introduced the change, but when I run `Pkg.test("Optim")` a test fails, but it does not fail if I write
```
using Optim, Base.Test
include("test/runtests.jl")
```
It's driving me nuts... :confused: :question:

**Comment by pkofod** [comment]
Thanks to `@Evizero` I found out that `Pkg.test("Optim")` runs with `--inline=no`. When I run the tests manually with this option, I get the same results as `Pkg.test`. Now I just need to find out why on earth the numerical results differ between turning it on and off (anyone care to make a guess? are we doing something we shouldn't? could it be `@simd` or `@inbounds` related?)

**Comment by johnmyleswhite** [comment]
How different are they? Inlining exposes a lot of additional information to LLVM that could be used to make other optimizations, so any optimization LLVM feels is provably correct should be on the table.

**Comment by pkofod** [comment]
Well, in the `inline=no` case, the objective increases (so it stops without convergence after the new option setup) and without it the objective strictly decreases and converges.

The thing is, this is for the laplacian problems _without_ preconditioning in `precon.jl`, so it is a pretty difficult problem to solve, and small pertubations might matter. I just didn't know turning inlining on or off could have numerical consequences like this. I will just allow the objective to increase for these tests then I guess.

**Comment by anriseth** [comment]
Another reason for allowing objective increases:)

An extension of this (for another day?) is to have allow a maximum number
of increases, and after that declare divergence.

**Comment by pkofod** [comment]
I actually just though about making it integer instead of Boolean. 0 default and then you can choose the number yourself. Kind of an exotic option (never seen it before elsewhere) but sure, for illconditioned problems it might help.

**Comment by anriseth** [comment]
This option is similar to the two options in PETSc, snes_max_linear_solve_fail and snes_max_fail, which allow a number of failures in computing the search direction (so not necessarily a direction of decrease), or a failure in the linesearch (e.g. not a sufficient decrease).

http://www.mcs.anl.gov/petsc/petsc-current/docs/manualpages/SNES/SNESSetFromOptions.html

**Comment by pkofod** [comment]
I consider it fixed for now. If anyone wants to allow for a specific number of increases they're welcome, but I'm not entirely sure how you would be able to know upfront that "5 increases is ok but 6 is not".
