### ISSUE TITLE
f_tol not working?

### ISSUE THREAD

**Issue by rgiordan** [JuliaOpt/Optim.jl#342]
I think lines 18 and 46 of ```assess_convergence``` is not actually assessing function convergence, since ```eps()``` is usually less than ```f_tol * (abs(f_x) + f_tol)```.

Just wanted to make sure I didn't misunderstand anything.  If this is in fact a bug, I'll put together a PR and unit test.

**Comment by pkofod** [comment]
Taken from https://github.com/JuliaOpt/Optim.jl/pull/303/files#diff-b0258ad6ba4c903377506f299c5f882dR18 . Is your suggestion to replace min with max? Such that it is the relative tolerance *unless* `eps` is larger than `rel_tol*diff`? @timholy

**Comment by rgiordan** [comment]
Yes, exactly.

**Comment by pkofod** [comment]
Not sure what happened there. Thanks for noticing. It would be wonderful if you would make the PR!

**Comment by rgiordan** [comment]
https://github.com/JuliaOpt/Optim.jl/pull/344
