### ISSUE TITLE
Suppressing Warning Messages

### ISSUE THREAD

**Issue by chenx26** [JuliaOpt/Optim.jl#343]
Hi,

I have been using Optim with "BFGS" option lately and it worked very well. However, when I use it on certain non-smooth problems (such as a smooth function plus L1 regularization) it gives a ton of warning messages about line search failed. Is there any way to turn the warning messages off?

Thanks,

Xin

**Comment by pkofod** [comment]
Great to hear you're using Optim. Warnings are sometimes annoying, but it seems like the software is whispering: you're running with scissors! It's fun and gets the job done a lot of the time, but it can also be dangerous.

The line searches are provided by our sister package LineSearches.jl (https://github.com/anriseth/LineSearches.jl/), so you could open an issue there.

**Comment by chenx26** [comment]
Thanks for the fast response. I will post the issue there.

Xin

**Comment by pkofod** [comment]
> Thanks for the fast response. I will post the issue there.
> 
> Xin

Any time. Out of curiosity, in what situation are you using it? Education or work?

**Comment by chenx26** [comment]
I am a PhD student in the Applied Math department at University of Washington. I am using Julia for part of the dissertation work, which involves quite a bit of optimization. 

Also, I closed the thread too fast. I found that the warning message is not raised by linesearch.jl, but rather [https://github.com/JuliaOpt/Optim.jl/blob/5b69eaeb084b07ea8396ab105e6661f4b850eb62/src/bfgs.jl#L98](url), it would nice to have an option like "warnings = false" to turn that off.

**Comment by anriseth** [comment]
I have two suggestions of how to handle the warnings atm:
- Checkout Optim's master branch. This includes a change to BFGS where the default behaviour is to start with step size 1.0 (#328). With the previvous behaviour, if the linesearch fails and your step size is almost zero, I think the next BFGS iteration would start with this "useless" step length as well. 
- Choose a different linesearch, I assume you are using `hagerzhang!` right now. Which one is best depends on the objective function.
  - `bt2!`, `bt3!`
  - These will not throw the warning:  `strongwolfe!`, `morethuente!`, `basic!`

**Comment by pkofod** [comment]
I'll tag again soon, but @chenx26  have you tried master?

**Comment by chenx26** [comment]
@pkofod I commented out [this line](https://github.com/JuliaOpt/Optim.jl/blob/5b69eaeb084b07ea8396ab105e6661f4b850eb62/src/bfgs.jl#L98) on my local machine 

@anriseth I tried the other line search methods. strongwolfe! and moretheuente! seem to work very well for my problem. Thanks for the suggestion!

**Comment by pkofod** [comment]
> @pkofod I commented out this line on my local machine and the warnings are gone now.

Alright. At least I've officially given a warning here :) Well, if it gets the job done, right?

You're welcome over at https://gitter.im/JuliaOpt/Optim.jl if you are looking for a place to discuss. You're also very welcome to open an issue in the future, if you encounter some problem.
