### ISSUE TITLE
Can I set the initial step size? 

### ISSUE THREAD

**Issue by misun6312** [JuliaOpt/Optim.jl#359]
Hello,

I want to change the initial step size to some smaller value than 1.
Is this possible with setting options?

I'm using Fminbox with Gradient Descent like below. 

```
res = optimize(d4, params, l, u, Fminbox(); 
optimizer = GradientDescent, optimizer_o = Optim.Options(g_tol = 1e-12,
                                                                        iterations = 100,
                                                                        show_every = true,
                                                                        store_trace = true,
                                                                        extended_trace = true,
                                                                        show_trace = true))

```

**Comment by pkofod** [comment]
Hi there,

With any of the default methods? I'll have to disappoint you with a no. The only way you can control it like that is by using the `basic!` line search "algorithm", that just sets the step size to a predetermined value (typically 1, but could be 0.1 or something else).

What you could do, is to define your own line search function. It would work around some of the logic for choosing the initial step-size, and this all depends on the solver and line search algorithm, so I cannot promise you how well it would work, but something like the following should "work" as in it will run
```julia
function my_line_search!(df, x, s, x_scratch, gr_scratch, lsr, alpha,
        mayterminate, c1, rhohi, rholo, iterations)
initial_alpha = 0.7
LineSearches.bt2!(df, x, s,x_scratch, gr_scratch, lsr, initial_alpha,
                  mayterminate, c1, rhohi, rholo, iterations)
end
``` 
I am basically defining my own line search function with the method signature that Optim expects (the right amount of inputs), and then I just manually overwrite the initial step size (alpha) with 0.7 and pass it to the cubic backtracking, but this could be whatever you prefer. Then I just pass it like I would normally do with a line search from LineSearches.jl:
```julia
function quadratic!(x, g, AtA, Atb, tmp)
    calc_grad = !(g === nothing)
    A_mul_B!(tmp, AtA, x)
    v = dot(x,tmp)/2 + dot(Atb,x)
    if calc_grad
        for i = 1:length(g)
            g[i] = tmp[i] + Atb[i]
        end
    end
    return v
end

srand(1)
N =  8
boxl = 2.0
l = fill(-boxl, N)
u = fill(boxl, N)

A = randn(N,N)
AtA = A'*A
b = randn(N)
initial_x = randn(N)
tmp = similar(initial_x)
func = (x, g) -> quadratic!(x, g, AtA, A'*b, tmp)
objective = Optim.DifferentiableFunction(x->func(x, nothing), (x,g)->func(x,g), func)
results = optimize(objective, initial_x, l, u, Fminbox(), optimizer = GradientDescent, linesearch = my_line_search!)
```

**Comment by anriseth** [comment]
Custom initial guess routines is proposed as a new feature, see for example #294 
No guarantee on when it will be implemented.

**Comment by pkofod** [comment]
Yeah, I'm sort of holding that back with #337 . I hope  I had time next week.

**Comment by misun6312** [comment]
Thanks @pkofod !!
But I got this error message if I run your example code. 
For me, it seems like it should work... with "Any" type, but it's not working!

```
MethodError: `my_line_search!` has no method matching my_line_search!(::Optim.DifferentiableFunction, ::Array{Float64,1}, ::Array{Float64,1}, ::Array{Float64,1}, ::Array{Float64,1}, ::LineSearches.LineSearchResults{Float64}, ::Float64, ::Bool)
Closest candidates are:
  my_line_search!(::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, !Matched::Any, !Matched::Any, !Matched::Any, !Matched::Any)
```

**Comment by pkofod** [comment]
Can you post your version of Optim and `versioninfo()` from Julia?

**Comment by misun6312** [comment]
Sure! I'm using Julia 0.4.5 and Optim (v0.7.4)

versioninfo()
```
Julia Version 0.4.5
Commit 2ac304d (2016-03-18 00:58 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i5-4258U CPU @ 2.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```


Pkg.status("Optim")
`Optim 0.7.4
`

**Comment by pkofod** [comment]
Sorry, it was my mistake, I've added a version with default values. Could you try again?

**Comment by misun6312** [comment]
Yay!! Now it's working :)  Thank you so much, @pkofod !!
Cool. I should update the package.

**Comment by pkofod** [comment]
Since this is a planned feature, I'm going to close this issue. Please reopen if you run into trouble.

**Comment by anriseth** [comment]
@misun6312 you can now choose your initial step length with the `alphaguess` keyword argument for `GradientDescent` and all other optimizers. Sorry that it took so long. It is currently only available in the `master` branch (`Pkg.checkout("Optim")`). 

If you want `GradientDescent` to always start its line search with step length 0.5, you call `GradientDescent(alphaguess = LineSearches.InitialStatic(alpha=0.5))`.

**Comment by misun6312** [comment]
Thank you @anriseth for the update!! This makes me get back to my project again :)

**Comment by anriseth** [comment]
> Thank you @anriseth for the update!! This makes me get back to my project again :)

Good to hear, @misun6312 . The available initial step length procedures are listed at https://github.com/JuliaNLSolvers/LineSearches.jl#available-initial-step-length-procedures 
There is some sparse documentation available. Call, for example, `help?> InitialStatic` in the REPL. 
If you have other types of Initial Step Length procedures that you are interested in, feel free to open an issue (or PR) over at https://github.com/JuliaNLSolvers/LineSearches.jl
