### ISSUE TITLE
Performance question

### ISSUE THREAD

**Issue by xiaohk** [JuliaOpt/Optim.jl#360]
I am implementing a one hidden unit neural network based on the Andrew Ng ML course. There are  5000 training examples,400 input units, 25 hidden units, and 10 output units. 

I have implemented a cost function, and a gradient function (using backward propagation to find the gradient). Then I pack two parameter matrices into a 10285 length vector, and try to use Optim.jl to find parameters to minimize the cost.

It turns out the minimize() call is pretty slow. I am wondering whether it is normal, and how can I improve it to actually find a minimum?

Below is the time measurement of 2 iterations.

```julia
julia> @time res = optimize(cost_optim, g!, rolling(init_weights()...), 
                      Optim.Options(iterations = 2))
 49.606044 seconds (1.23 G allocations: 26.956 GB, 4.28% gc time)
Results of Optimization Algorithm
 * Algorithm: BFGS
 * Starting Point: [-0.078,0.0075, ...]
 * Minimizer: [-0.08271276513225419,0.000560325701996895, ...]
 * Minimum: 3.245835e+00
 * Iterations: 2
 * Convergence: false
   * |x - x'| < 1.0e-32: false
   * |f(x) - f(x')| / |f(x)| < 1.0e-32: false
   * |g(x)| < 1.0e-08: false
   * Reached Maximum Number of Iterations: true
 * Objective Function Calls: 8
 * Gradient Calls: 8

julia> @time res = optimize(cost_optim, g!, rolling(init_weights()...), 
                      Optim.Options(iterations = 2))
 49.350775 seconds (1.23 G allocations: 26.905 GB, 5.00% gc time)
Results of Optimization Algorithm
 * Algorithm: BFGS
 * Starting Point: [-0.0885,0.0603, ...]
 * Minimizer: [-0.10100774234693083,0.040918413843693, ...]
 * Minimum: 3.249942e+00
 * Iterations: 2
 * Convergence: false
   * |x - x'| < 1.0e-32: false
   * |f(x) - f(x')| / |f(x)| < 1.0e-32: false
   * |g(x)| < 1.0e-08: false
   * Reached Maximum Number of Iterations: true
 * Objective Function Calls: 8
 * Gradient Calls: 8
```

**Comment by KristofferC** [comment]
How much time does it take to evaluate your function / gradient? If that is slow, there is nothing Optim can do.

**Comment by xiaohk** [comment]
```julia
julia> @time cost_optim(inp)
  0.117787 seconds (299.02 k allocations: 34.630 MB, 3.32% gc time)
6.731678353620617

julia> @time g!(inp, store)
  0.462285 seconds (249.05 k allocations: 842.371 MB, 23.69% gc time)
10285-element Array{Float64,1}:
 -0.00500067 
 -0.0117951  
  0.00950344 
  0.00822108 
 -0.0289155  
 -0.0193242  
  0.00324327 
  0.024644   
  0.000829144
  0.0228536  
  ⋮          
  0.182284   
  0.173855   
  0.160339   
  0.184936   
  0.206257   
  0.183463   
  0.181075   
  0.236048   
  0.171769 
```

Yeah it seems they are kinda slow already. The tutorial uses Octave 's `fmincg()` function to find the minimum, and it seems doable.

**Comment by KristofferC** [comment]
Maybe you just implemented your functions in a non performant way. Your gradient function allocates almost a gigabyte of data...

**Comment by johnmyleswhite** [comment]
We get a lot of these kinds of questions and the solution is almost invariably to improve the code for the function being optimized. Perhaps we should split out the timing information into:

* Total time spent
* Time spent evaluating functions
* Time spent in Optim.jl

That would likely clarify to users where the performance problems are.
