### ISSUE TITLE
Benchmarks?

### ISSUE THREAD

**Issue by IainNZ** [JuliaOpt/Optim.jl#37]
So I just presented JuliaOpt at the CAJUN meeting and the first question I got was "how does L-BFGS perform?" and I had to say "probably pretty good"(!)
Is there a good way to go about benchmarking it versus something else? Maybe even NLOpt?

**Comment by johnmyleswhite** [comment]
Coming back to this, I'm not very interested in benchmarks against other systems for now and mostly interested in benchmarks that let us assess for ourselves whether the changes we make are useful. Will elaborate more in another issue.

**Comment by pkofod** [comment]
I'm closing this issue in favour of #223 #259.
