### ISSUE TITLE
minimum versus minimizer

### ISSUE THREAD

**Issue by jstac** [JuliaOpt/Optim.jl#76]
Just a suggestion: In optimization theory, 'minimum' is the minimal value of a function, while the point that attains the minimum is called the 'minimizer'.  So in this code ``res = optimize(objective, 0.0 1.0)``, you might save a lot of future confusion by changing ``res.minimum`` to ``res.minimizer``.

**Comment by johnmyleswhite** [comment]
We should address this soon with a formal API that uses correct terminology.
