### ISSUE TITLE
extra cg arguments in fminbox

### ISSUE THREAD

**Issue by Ken-B** [JuliaOpt/Optim.jl#89]
I was adapting my little [MinFinder](https://github.com/Ken-B/MinFinder.jl) algorithm to the new `fminbox` API and I noticed that the remaining `cg` function has 3 more arguments than the generic `optimize` currently allows. These are `eta`, `P` and `precondprep`. 

Changing the `optimizer=cg` keyword argument in `fminbox` to another method fails with
```julia
unrecognized keyword argument "eta"
```

How about adding these 3 arguments to the `optimize` function definition and using optimize with `method=optimizer` in `fminbox` instead of the current `optimizer`? @timholy, I believe you wrote this code and if you want I can help with writing this in a PR if you agree. You probably also know better how this will play with your pending PR #50.

Slightly related, I saw `optimize.jl` is pretty verbose, and that this change will add even a few more lines to it. Maybe this calls for a rewrite? 
I can assist here if someone has a good idea for it.

**Comment by Rory-Finnegan** [comment]
Just wondering if anyone has made any progress on this issue. If not I could probably do it, as I'm trying to get `l_bfgs` working with `fminbox`.

**Comment by mlubin** [comment]
See #149

**Comment by pkofod** [comment]
Is #205 something along he lines of what you had in mind @Ken-B?

**Comment by Ken-B** [comment]
Gosh, this was almost 2 years ago, so your guess is as good as mine of what I had in mind then ;-)

I believe the reason I opened this issue was that I was using fminbox in a package and I wanted to be able to pass through optimization arguments. It seems the #205 does this.
I would have to update that package to julia 0.4/0.5 to see if it works with the new changes, maybe this is a good reason to do so.

Anyway, I'll close this issue now and open a new issue in case I hit a problem with updating MinFinder. Thanks for cleaning up these old issues!
