### ISSUE TITLE
Extra arguments to objective/gradient/hessian functions

### ISSUE THREAD

**Issue by bdeonovic** [JuliaOpt/Optim.jl#94]
I didn't see any examples in the documentation that showed how you can optimize an objective function (with corresponding gradient and hessian) that depends on some variables you are not trying to optimize on. 

What is the appropriate way to handle such a situation?

**Comment by mlubin** [comment]
#90 #85 #53
We definitely need an FAQ on this.

**Comment by johnmyleswhite** [comment]
Agreed.

**Comment by johnmyleswhite** [comment]
Subsuming in broader documentation issue.
