### ISSUE TITLE
Warnings when used with julia0.4

### ISSUE THREAD

**Issue by bastikr** [JuliaOpt/Optim.jl#96]
I couldn't find any mention of it in the julia mailing lists but apparently the {} notation should not be used for Any[] anymore. With julia0.4 I get many warnings of the following kind:

WARNING: deprecated syntax "{a,b, ...}" use "Any[a,b, ...]" instead.

This is a little bit annoying since it unnecessarily litters up the terminal.

**Comment by johnmyleswhite** [comment]
Please don't use Julia 0.4. The official release is 0.3 and you should be using that.

**Comment by pkofod** [comment]
Fixed in #138
