### ISSUE TITLE
Overloading Base.dot

### ISSUE THREAD

**Issue by bastikr** [JuliaOpt/Optim.jl#97]
Optim.jl overloads the Base.dot function with this method

    # Dot product of two "vectors", even if they don't have a vector shape
    function dot(x::Array, y::Array)
       d = x[1] * y[1]
        for i = 2:length(x)
            d += x[i] * y[i]
        end
        return d
    end

Therefore when using Optim the following might happen

    julia> dot([1,2], [3 4 5])
    11

This is a behavior that I definitely don't expect and really don't want to have. Would it maybe be possible to not overload Base.dot but just use it internally in Optim?

**Comment by johnmyleswhite** [comment]
Let me think about this. We could define our own `dot` that falls back on Base for cases when Base is defined and adds additional cases that `Base` is missing.

That said, what exactly is the thing you dislike about this definition? Your definition suggests what troubles you is the possibility of doing `dot` with two objects of unequal sizes. If we removed that, would your problems go away?

**Comment by bastikr** [comment]
Coming from numpy I assumed that the dot function would work as matrix multiplication given a vector and a matrix as arguments. Including Optim.jl and doing dot(Vector, Matrix) gives a surprising result which, in my case, only lead to an error a few lines further. In Base the dot function is simply undefined for this case which immediately would have guided me to look up how to do it correctly.
In my opinion it's unclean if a module has unforeseen side-effects. It's perfectly fine overloading Base functions if some of the arguments are types which are provided by the module. But in this case I found it a little bit annoying. (I hope that didn't sound too harsh)

**Comment by mlubin** [comment]
I agree that it's not really appropriate for Optim to define a new general meaning of ``dot`` that's not in base Julia.

**Comment by johnmyleswhite** [comment]
We certainly can clean that up. The question is whether a variant of the behavior we currently use that definition for might actually be desirable to have in Base. Right now you can use Optim to optimize arrays and not just vectors thanks to our use of generalized definition of `dot`. We can rename that operation and only use it internally, but I wonder if we should just try to include it in Base.

**Comment by andreasnoack** [comment]
Inclusion in base would probably touch on https://github.com/JuliaLang/julia/issues/4774 which nobody knows when will be closed.

For now, it would probably be good to change Optim's `dot` to ensure that the dimensions fit together and, at least, that the length of the two arrays are the same.
